name: Test

# Removed push and pull_request triggers for master to prevent duplicate workflows
on: [workflow_dispatch] # Example: Keep for manual triggers

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: poetry install

    - name: Initialize database
      run: |
        poetry run bash scripts/init_db.sh
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: localhost
        DB_NAME: gsg

    - name: Run tests
      run: poetry run pytest
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/gsg 